cart/urls.py
from django.urls import path
from .views import (
    ShippingAddressView,
    addCouponView,
    PaymentView,
)

app_name = 'cart'

urlpatterns = [
    path('address/', ShippingAddressView.as_view() , name='address'),
    path('add-coupon/', addCouponView.as_view() , name='add-coupon'),
    path('payment/', PaymentView.as_view(), name='payment'  )
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from page.views import home
from django.conf import settings
from django.conf.urls.static import static
from product.views import category_show

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls', namespace='user'),),
    path('cart/', include('cart.urls'), ), 
    path('product/', include('product.urls'), ), 
    path('', include('page.urls'),), 
    path('<slug:category_slug>', category_show, name="category_show"),
] + static( 
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

product/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    add_to_cart,
    remove_single_item,
    remove_from_cart,
    OrderSummaryView
)

app_name = 'product'

urlpatterns = [
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add_to_cart' ),
    path('remove_single_item/<slug:slug>', remove_single_item, name="remove_single_item"),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),
    path('summary/', OrderSummaryView.as_view(), name='summary'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.core import validators
from tinymce.widgets import TinyMCE
from product.models import (
    BillingAddress, 
    Coupon,
    #Cities
)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Coupon code'
    }))
    



class ShippingAddressForm(forms.ModelForm):
    address_text = forms.CharField(widget=forms.Textarea(
        attrs={'rows':5, 'cols':25}), label="Adres")

    class Meta:
        model = BillingAddress
        fields = [
            'country',
            'city',
            'town',
            'district',
            'postal_code',
            'address_text'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['city'].queryset = Cities.objects.none()
        #self.fields['town'].queryset = Cities.objects.none()
        #self.fields['district'].queryset = Cities.objects.none()
        

cart/views.py
from django.shortcuts import render,redirect, get_list_or_404
from django.views.generic import  ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.contrib import messages 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse, HttpResponse
from product.models import (
    Order,
    BillingAddress,
    Coupon,
    Payments,
    Cities,
)
import json
from .forms import (
    ShippingAddressForm,
    CouponForm,
)

import stripe
import random
import string
import config

stripe.api_key = config.settings.STRIPE_SECRET_KEY

def create_order_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=12))

#@login_required(login_url='accounts:login_view')
class ShippingAddressView(LoginRequiredMixin, View):
    def get(self,*args, **kwargs):
        try:
            order = Order.objects.get(
                user=self.request.user, 
                ordered=False
            )
            form = ShippingAddressForm()
            couponform = CouponForm()
            context = dict(
                form=form,
                order=order,
                couponform=couponform,
                display_coupon_form=True,
            )
            context['title'] = "Adres Bilgilerini Getir"
            if self.request.method == 'POST':
                form = ShippingAddressForm(self.request.POST or None, self.request.FILES or None)    
                if form.is_valid():
                    f = form.save(commit=False)
                    f.user = self.request.user
                    f.save()
            context = dict(
                form=form,
                order=order,
                couponform=couponform,
                display_coupon_form=True,
            )
            return render(self.request, 'cart/shipping_address.html', context)
        except ObjectDoesNotExist:
            messages.info(self.request, 'Aktif siparişiniz yok')
            return redirect('product:summary')
        
    def post(self, *args, **kwargs):
        try:
            form = ShippingAddressForm(self.request.POST or None)
            order = Order.objects.get(
                user=self.request.user, 
                ordered=False
            ) 
            if form.is_valid():
                country = form.cleaned_data.get('country')
                city = form.cleaned_data.get('city')
                town = form.cleaned_data.get('town')
                district = form.cleaned_data.get('district')
                postal_code = form.cleaned_data.get('postal_code')
                address_text = form.cleaned_data.get('address_text')

                billing_address = BillingAddress(
                    user=self.request.user,
                    country=country,
                    city=city,
                    town=town,
                    district=district,
                    postal_code=postal_code,
                    address_text=address_text
                )

                billing_address.save()
                order.billing_address = billing_address
                order.save()

                messages.info(self.request, 'Sipariş adresiniz eklendi')
                return redirect('cart:payment')
        except ObjectDoesNotExist:
            messages.info(self.request, 'Aktif siparişiniz yok')
            return redirect('product:summary')
    

def get_coupon(request, code):
    try:
        coupon = Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        messages.info(request, 'Bu kupon geçerli değildir.')
        return redirect('product:summary')


class addCouponView(View):
    def post(self, *args, **kwargs):
        form = CouponForm(self.request.POST or None)
        if form.is_valid():
            try:
                code = form.cleaned_data.get('code')
                order = Order.objects.get(user=self.request.user, ordered=False)
                order.coupon = get_coupon(self.request, code)
                order.save()
                messages.success(self.request, 'Coupon eklendi')
                return redirect('cart:address')
            except ObjectDoesNotExist:
                messages.success(self.request, "Geçerli bir siparişiniz yok")
                return redirect('product:summary')
            

class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.billing_address:
            context = {
                'order': order,
                'display_coupon_form' : False,
            }
            return render(self.request, 'cart/payment.html', context)
        else:
            messages.warning(self.request, 'Lütfen bir adres ekleyin')
            return redirect('cart:address')

    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripeToken')
        amount = int(order.total_price() * 100)
        print("-"*100)
        #print(stripe.Customer.list())
        print(token)
        print(amount)
        print("-"*100)

        try:
            charge = stripe.Charge.create(
                amount=amount,
                currency='usd',
                source=token,
                description='DjangoE-Trade Ödeme'
            ) 
            #print(charge)
            print("-"*100)
            payment = Payments()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = order.total_price()

            print("="*100)
            print("payment:", payment)
            print(payment.stripe_charge_id)
            print(payment.user)
            print(payment.amount)
            print("="*100)

            order_items = order.items.all()
            order_items.update(ordered=True)

            for item in order_items: 
                item.save()

            order.ordered = True
            order.payment = payment

            order.order_ref = create_order_code()
            payment.save()
            order.save()

            messages.success(self.request, 'Siparişiniz alındı')
            return redirect('/')

        except stripe.error.CardError as e :
            body = e.json_body
            err = body.get('error', {})
            messages.warning(self.request, f"{err.get('message')}")
            return redirect('cart:payment')
        except stripe.error.RateLimitError as e : 
            messages.warning(self.request, 'Rate Limit Error')
            return redirect('cart:payment')
        except stripe.error.InvalidRequestError as e : 
            messages.warning(self.request, 'Geçersiz parametre')
            print('invalid parameters', e)
            print('the value is ', amount)
            return redirect('cart:payment')
        except stripe.error.AuthenticationError as e : 
            messages.warning(self.request, 'Not authenticated')
            return redirect('cart:payment')
        except stripe.error.APIConnectionError as e : 
            messages.warning(self.request, 'Network Error')
            return redirect('cart:payment')
        except stripe.error.StripeError as e : 
            messages.warning(self.request, 'Something went wong, you were not charged, please try again!')
            return redirect('cart:payment')
        except Exception as e :
            messages.warning(self.request, 'Something went wong, we will work about it since we have been notified')
            return redirect('cart:payment')

cart/templates/cart/cart_coupon_snippet.html
{% load crispy_forms_tags %}

<h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">
        Sepetiniz
    </span>
    <span class="badge bg-dark text-white ms-1 rounded-pill">
        {{ order.items.count }}
    </span>
</h4>

<!--CART-->

<ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all  %}
    <li class="list-group-item d-flex justify-content-between 
        lh-condensed   bg-info bg-opacity-10">
        <div class="container">
            <h6 class="my-0">
                {{ order_item.quantity }} x {{ order_item.item.title }}
            </h6>
            <small class="text-muted">{{ order_item.item.snip_description }}</small>
        </div>
        <span class="text-muted">{{ order_item.final_price }}</span>
    </li>
    {% endfor %}

    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
            <h6 class="my-0">
                Promosyon Kodu
            </h6>
            <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-{{ order.coupon.amount }}</span>
    </li>
    {% endif %}

    <li class="list-group-item d-flex justify-content-between 
            bg-info bg-opacity-50">
        <span>Tutar (TL)</span>
        <strong>{{ order.total_price }} TL</strong>
    </li>
</ul>

<!--promosyon kodu-->
{% if display_coupon_form %}
    <form action="{% url 'cart:add-coupon' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <p>&nbsp;</p>
            <h5>Promosyon Kodu Uygula</h5>
        </div>
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-addon ml-2">
                <button class="btn btn-info m-0" type="submit">Uygula</button>
            </div>
        </div>
    </form>
{% endif %}

cart/templates/cart/payment.html
{% extends 'core/base.html' %}

{% block container-fluid %}
<style>
    #stripeBtnLabel {
        font-family: "Helvetica Neue", Helvetica, sans-serif;
        font-size: 16px;
        font-variant: normal;
        padding: 0;
        margin: 0;
        -webkit-font-smoothing: antialiased;
        font-weight: 500;
        display: block;
    }

    #stripeBtn {
        border: none;
        border-radius: 4px;
        outline: none;
        text-decoration: none;
        color: #fff;
        background: #32325d;
        white-space: nowrap;
        display: inline-block;
        height: 40px;
        line-height: 40px;
        box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
        border-radius: 4px;
        font-size: 15px;
        font-weight: 600;
        letter-spacing: 0.025em;
        text-decoration: none;
        -webkit-transition: all 150ms ease;
        transition: all 150ms ease;
        float: left;
        width: 100%
    }

    button:hover {
        transform: translateY(-1px);
        box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
        background-color: #43458b;
    }

    .stripe-form {
        padding: 5px 30px;
    }

    #card-errors {
        height: 20px;
        padding: 4px 0;
        color: #fa755a;
    }

    .stripe-form-row {
        width: 100%;
        float: left;
        margin-top: 5px;
        margin-bottom: 5px;
    }

    .StripeElement {
        box-sizing: border-box;

        height: 40px;

        padding: 10px 12px;

        border: 1px solid transparent;
        border-radius: 4px;
        background-color: white;

        box-shadow: 0 1px 3px 0 #e6ebf1;
        -webkit-transition: box-shadow 150ms ease;
        transition: box-shadow 150ms ease;
    }
</style>

<section class="py-5 container">
    <div class="row">

        <div class="col-sm-6">

            <h4 class="mb-4">Ödeme | Kredi Kartı Bilgileri</h4>
            <hr>
            <div class="new-card-form">
                <form action="." method="post" class="stripe-form" id="stripe-form">
                    {% csrf_token %}
                    <div class="stripe-form-row" id="creditCard">
                        <label for="card-element" id="stripeBtnLabel">
                            Kredi veya banka kartı
                        </label>
                        <div id="card-element" class="StripeElement StripeElement--empty">
                            <div class="__PrivateStripeElement"
                                style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                                <iframe frameborder="0" allowtransparency="true" scrolling="no"
                                    name="__privateStripeFrame5" allowpaymentrequest="true"
                                    src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1"
                                    title="Secure payment input frame"
                                    style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe>
                                <input class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" "
                                    autocomplete="false" maxlength="1"
                                    style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                            </div>
                        </div>
                    </div>
                    <div class="stripe-form-row">
                        <button id="stripeBtn">Öde</button>
                    </div>
                    <div class="stripe-form-row">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" name="save" id="save_card_info">
                            <label class="custom-control-label" for="save_card_info">Save for future purchases</label>
                        </div>
                    </div>
                    <div id="card-errors" role="alert"></div>
                </form>
            </div>


        </div><!--sm-6-->

        <div class="col-sm-6">
            {% include 'cart/cart_coupon_snippet.html' %}
        </div>

    </div><!--container-->
</section>

{% endblock container-fluid %}


{% block more_scripts %}
<script src="https://js.stripe.com/v3/"></script>
<script nonce="">  // Create a Stripe client.
    var stripe = Stripe('pk_test_YOUR_STRIPE_KEY_ADD_HERE');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
        base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
                color: '#aab7c4'
            }
        },
        invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
        }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', { style: style });

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function (event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
    });

    // Handle form submission.
    var form = document.getElementById('stripe-form');
    form.addEventListener('submit', function (event) {
        event.preventDefault();

        stripe.createToken(card).then(function (result) {
            if (result.error) {
                // Inform the user if there was an error.
                var errorElement = document.getElementById('card-errors');
                errorElement.textContent = result.error.message;
            } else {
                // Send the token to your server.
                stripeTokenHandler(result.token);
            }
        });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('stripe-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
    }


</script>

{% endblock more_scripts %}

cart/templates/cart/shipping_address.html
{% extends 'core/base_without_navbar.html' %}
{% load crispy_forms_tags %}
{% block container-fluid %}
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-6 mt-5">
            <h2 class="mb-4">Adres Bilgileri:</h2>
            <hr>
            <p>&nbsp;</p>

            {% if order.billing_address %}
                <p>Ekli bir adresiniz var<i> 
                    <b>{{ order.billing_address.address_text }}</b>
                </i>  Bu adresi değiştirmek istiyor musunuz?
                <p>&nbsp;</p>
                <p>&nbsp;</p>   
                <hr>
                <a href="" class="btn btn-warning ml-5">Adres Değiştir</a>
                <a href="{% url 'cart:payment' %}" class="btn btn-info">Ödemeye Devam Et</a>
                </p>
            {% else %}

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'product:summary' %}" class="btn btn-secondary">İptal</a>
                <button type="submit" class="btn btn-primary btn-lg">Kaydet</a>
            </form>
            {% endif %}
        </div>
        <div class="col-sm-6 mt-5">
            {% include 'cart/cart_coupon_snippet.html' %}
        </div>
    </div>
</div>
{% endblock container-fluid %}

{% comment %}

<style>
    body {
        width: 100%;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    #my_form {
        width: auto;
        padding: 40px 40px;
        border-radius: 20px;
        box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
    }

    input {
        width: 400px;
    }
</style>

{% endcomment %}

{% comment %}
<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');



    let country_field = document.getElementById("id_country")
    country_field.addEventListener("change", getCountryId)


    function getCountryId(e) {
        console.log(e.target.value)
        let country_id = e.target.value

        const data = { id: country_id };

        let url = " {% url 'cart:cities' %} "


        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify(data),
        })

            .then(response => response.json())

            .then(data => {
                console.log('Success ', data);
            })

            .catch((error) => {
                console.error('Error:', error);
            });

    }

    let input = document.getElementById('id_name')
    let select = document.getElementById('select')
    console.log(select)

    input.classList.add("form-control")
    for (let i = 0; i < select.length; i++) {
        select[i].classList.add("form-select")
    }

</script>
{% endcomment %}