accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login_view'),
    path('register/', register_view, name='register_view'),
    path('logout/', logout_view, name='logout_view'),
]

cart/urls.py
from django.urls import path
from .views import (
    ShippingAddressView,
    addCouponView,
    PaymentView,
)

app_name = 'cart'

urlpatterns = [
    path('address/', ShippingAddressView.as_view() , name='address'),
    path('add-coupon/', addCouponView.as_view() , name='add-coupon'),
    path('payment/', PaymentView.as_view(), name='payment'  )
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from page.views import home
from django.conf import settings
from django.conf.urls.static import static
from product.views import category_show

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls', namespace='user'),),
    path('cart/', include('cart.urls'), ), 
    path('product/', include('product.urls'), ), 
    path('', include('page.urls'),), 
    path('<slug:category_slug>', category_show, name="category_show"),
] + static( 
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

product/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    add_to_cart,
    remove_single_item,
    remove_from_cart,
    OrderSummaryView
)

app_name = 'product'

urlpatterns = [
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add_to_cart' ),
    path('remove_single_item/<slug:slug>', remove_single_item, name="remove_single_item"),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),
    path('summary/', OrderSummaryView.as_view(), name='summary'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='detail'),
]

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DJANGO ETRADE</title>
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
  <body>
    {% include 'page/components/message.html' %}
    {% include 'core/navbar.html' %}
    
    {% block container-fluid %}
    {% endblock container-fluid %}

    {% include 'core/footer.html' %}
    <!-- BOOTSTRAP JS -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block script %}
    {% endblock %}

    {% block more_scripts %}
    {% endblock %}

  </body>
</html>

templates/core/base_without_navbar.html
{% load static %}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> kaftClone </Kbd></title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% include 'core/messages.html' %}
    {% include 'core/navbar.html' %}
    
    {% block container-fluid %}
    {% endblock container-fluid %}

    {% include 'core/footer.html' %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/core/footer.html
<div class="bg-dark py-5 mt-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h3 class="text-light">Urun Ozellikleri</h3>
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="">T-Shirt</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="">Bere</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="">Canta</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-4">
                
                <form class="form-inline">
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="ebulten" class="sr-only">E-Bulten</label>
                        <input type="email" class="form-control" id="ebulten" placeholder="mail adresin">
                    </div>
                    <button type="submit" class="btn btn-dark mb-2">Kaydol</button>
                    </form>

            </div>
        </div>

        <div class="row border-top mb-3"></div>
        <div class="row">
            <div class="col-sm-2">
                <h5 class="text-light">Erkek</h5>
                <ul class="list-unstyled">
                    {% for item in categories %}
                    {% if item.gender == "men" or item.gender == "unisex" %}
                    <li>
                    <a class="list-item" href="{% url 'category_show' category_slug=item.slug %}">
                        {{ item.title }}
                    </a>
                    </li>
                    {% endif %}
                  {% endfor %}  
                </ul>
            </div>
            <div class="col-sm-2">
                <h5 class="text-light">Kadin</h5>
                <ul class="list-unstyled">
                    {% for item in categories %}
                    {% if item.gender == "women" or item.gender == "unisex" %}
                    <li>
                    <a class="list-item" href="{% url 'category_show' category_slug=item.slug %}">
                        {{ item.title }}
                    </a>
                    </li>
                    {% endif %}
                  {% endfor %}  
                </ul>
            </div>
            <div class="col-sm-2">
                <h5 class="text-light">Her Zaman</h5>
                <ul class="list-unstyled">
                    {% for item in categories %}
                    {% if item.gender == "unisex" %}
                    <li>
                    <a class="list-item" href="{% url 'category_show' category_slug=item.slug %}">
                        {{ item.title }}
                    </a>
                    </li>
                    {% endif %}
                  {% endfor %}  
                </ul>
            </div>
            <div class="col-sm-2">
                <h5 class="text-light">Bilgi</h5>
                <ul class="list-unstyled">
                    {% for item in pages %}
                    <li>
                        <a href="{% url 'page_show' slug=item.slug %}">
                            {{ item.title }}
                        </a>
                    </li> 
                    {% endfor %}    
                    
                </ul>
            </div>
            <div class="col-sm-2">
                <h5 class="text-light">Yardim</h5>
                <ul class="list-unstyled">
                    <li><a href="">Consequatur, eius pariatur.</a></li>
                    <li><a href="">Quaerat, reprehenderit quam.</a></li>
                    <li><a href="">Harum, maxime eum.</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5 class="text-light">Sosyal Medya</h5>
                <ul class="list-unstyled text-white">
                    <li><a href="" >Maxime, ullam iusto.</a></li>
                    <li><a href="" >Voluptatum, vel voluptas.</a></li>
                    <li><a href="" >Non, nemo omnis.</a></li>
                </ul>
            </div>
        </div>

    </div>
</div>

templates/core/messages.html
{% if messages %}
    {% for message in messages%}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }} </strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

templates/core/navbar.html
<div class="bg-dark">
    <div class="container">
<nav class="navbar navbar-expand-lg navbar-dark ">
        <a class="navbar-brand" href="{% url 'home' %}">DjangoE-Trade</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">
                Bak <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="" aria-expanded="">
                    Erkek
                </a>
                <div class="dropdown-menu " x-placement="bottom-start" >
                  {% for item in categories %}
                    {% if item.gender == "men" or item.gender == "unisex" %}
                      <a class="dropdown-item" href="{% url 'category_show' category_slug=item.slug %}">
                        {{ item.title }}
                      </a>
                    {% endif %}
                  {% endfor %}  
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="" aria-expanded="">
                    Kadın
                </a>
                <div class="dropdown-menu " x-placement="bottom-start" >
                  {% for item in categories %}
                    {% if item.gender == "women" or item.gender == "unisex" %}
                    <a class="dropdown-item" href="{% url 'category_show' category_slug=item.slug %}">
                        {{ item.title }}
                      </a>
                    {% endif %}
                  {% endfor %}  
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="" aria-expanded="">
                    Her Zaman
                </a>
                <div class="dropdown-menu " x-placement="bottom-start" >
                  {% for item in categories %}
                    {% if item.gender == "unisex" %}
                    <a class="dropdown-item" href="{% url 'category_show' category_slug=item.slug %}">
                        {{ item.title }}
                      </a>
                    {% endif %}
                  {% endfor %}  
                </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder='Senin İçin'>
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Bul</button>
          </form>

          <div class="navbar-nav ms-auto">
            {% if not request.user.is_authenticated %}
                <a 
                    class="nav-link" 
                    href="{% url 'accounts:login_view' %} ">
                Giriş
                </a>
                <a 
                    class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" 
                    href="{% url 'accounts:register_view' %}">
                Üye Ol
                </a>
            {% else %}
                <a class="nav-link" href="#">{{ request.user.username }}</a>
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" href=" {% url 'accounts:logout_view' %} ">Logout</a>

                <a href="{% url 'product:summary' %}" class="btn btn-secondary" type="submit">
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                       fill="currentColor" class="bi bi-cart4 " viewBox="0 0 16 16">
                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                  </svg>
                 
                  <i class="bi bi-cart-fill me-1"></i>
                </a>
            {% endif %}
        </div>
        </div>
      </nav>
    </div>
</div>