cart/urls.py
from django.urls import path
from .views import (
    ShippingAddressView,
    addCouponView,
    PaymentView,
)

app_name = 'cart'

urlpatterns = [
    path('address/', ShippingAddressView.as_view() , name='address'),
    path('add-coupon/', addCouponView.as_view() , name='add-coupon'),
    path('payment/', PaymentView.as_view(), name='payment'  )
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from page.views import home
from django.conf import settings
from django.conf.urls.static import static
from product.views import category_show

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls', namespace='user'),),
    path('cart/', include('cart.urls'), ), 
    path('product/', include('product.urls'), ), 
    path('', include('page.urls'),), 
    path('<slug:category_slug>', category_show, name="category_show"),
] + static( 
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

product/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    add_to_cart,
    remove_single_item,
    remove_from_cart,
    OrderSummaryView
)

app_name = 'product'

urlpatterns = [
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add_to_cart' ),
    path('remove_single_item/<slug:slug>', remove_single_item, name="remove_single_item"),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),
    path('summary/', OrderSummaryView.as_view(), name='summary'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='detail'),
]

product/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User


# Third Party Apps:
from django.urls import reverse
from page.models import DEFAULT_STATUS, STATUS


GENDER_CHOICE = [
    ('men', 'Erkek'),
    ('women', 'Kadin'),
    ('unisex', 'UniSex'), 
]


class BaseModel(models.Model):
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        abstract = True



# Category
class Category(models.Model):
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        default=DEFAULT_STATUS,
        choices=STATUS,
        max_length=10,
    )
    gender = models.CharField(
        max_length=6,
        default="unisex",
        choices=GENDER_CHOICE,
    )
    slug = models.SlugField(
        max_length=200,
        default="",
    )
    
    def __str__(self): 
        return f"{self.pk} - {self.gender} - {self.title}"


    def get_absolute_url(self):
        return reverse(
            'page:page_view',
            kwargs={
                'page_slug':self.slug,
            }
        )
    

# Product / Item
class Product(models.Model):
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    product_code = models.CharField(max_length=50) #ürün kodu
    price = models.FloatField()   #birim fiyat
    discount_price = models.FloatField(blank=True, null=True) #indirim
    category = models.ForeignKey(
        Category, 
        on_delete=models.CASCADE
    )
    brand = models.CharField(max_length=50) #Marka
    content = models.TextField()
    cover_image = models.ImageField(
        upload_to='product',
        null=True,
        blank=True,
    )
    slug = models.SlugField(
        max_length=200,
        default="",
    )
    stock = models.PositiveSmallIntegerField(default=0)
    is_home = models.BooleanField(default=False)
    status = models.CharField(
        default=DEFAULT_STATUS,
        choices=STATUS,
        max_length=10,
    )
    
    def __str__(self): 
        return self.title

    def get_discount_percent(self):
        discount_percent = 100 - (self.discount_price * 100 / self.price)
        return discount_percent

    def get_item_url(self):      
        return reverse('product:detail', kwargs={
            'slug' : self.slug
        })
    
    
    def get_add_to_cart(self):
        return reverse('product:add_to_cart', kwargs={
            'slug' : self.slug
        })
    

    def snip_description(self):
        return self.content[:30] + "..."
    

#OrderItem
class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False) #status
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def  __str__(self) :
        return f"{self.quantity} - {self.item.title}"
    
    def total_item_price(self):
        return self.quantity * self.item.price
    
    def total_item_discount_price(self):
        return self.quantity * self.item.discount_price
    
    def amount_saved(self): 
        return self.total_item_price() - self.total_item_discount_price()
    
    def final_price(self):
        if self.item.discount_price:
            return self.total_item_discount_price()
        return self.total_item_price()


#Country
class Countries(models.Model):
    country = models.CharField(max_length=50)

    def  __str__(self) :
        return self.country

#cities
class Cities(models.Model):
    country_id = models.ForeignKey(Countries, on_delete=models.CASCADE)
    city = models.CharField(max_length=50)

    def  __str__(self) :
        return self.city
    
#Towns
class Towns(models.Model):
    city_id = models.ForeignKey(Cities, on_delete=models.CASCADE)
    town = models.CharField(max_length=50)

    def  __str__(self) :
        return self.town

#Districts
class Districts(models.Model):
    town_id = models.ForeignKey(Towns, on_delete=models.CASCADE)
    district = models.CharField(max_length=50)

    def  __str__(self) :
        return self.district

#Address
class BillingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    country = models.ForeignKey(Countries, on_delete=models.CASCADE)
    city = models.ForeignKey(Cities, on_delete=models.CASCADE)
    town = models.ForeignKey(Towns, on_delete=models.CASCADE)
    district = models.ForeignKey(Districts, on_delete=models.CASCADE)
    postal_code = models.CharField(max_length=10)
    address_text = models.CharField(max_length=500)


#Coupon
class Coupon(models.Model):
    code = models.CharField(max_length=20)
    amount = models.FloatField()
    
    def __str__(self):
        return self.code


#Payments
class Payments(models.Model):
    stripe_charge_id = models.CharField(max_length=100)
    user = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True
    )
    #payment_type = models.SmallIntegerField(blank=True, null=True)
    #isok = models.BooleanField()
    #approve_code = models.CharField(max_length=100)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

#Order
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_ref = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem) 
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False) #status
    billing_address = models.ForeignKey(
        BillingAddress, 
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True
    )
    coupon = models.ForeignKey(
        Coupon, 
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True
    )
    payment = models.ForeignKey(
        Payments,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def  __str__(self) :
        return self.user.username

    def total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.final_price()

        if self.coupon:
            total -=  self.coupon.amount
        return total
  
  

#Refund
class Refund(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk}"

    

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import (
    Category, 
    Product,
    Order,
    OrderItem,
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages 
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist


STATUS = "published"

def category_show(request, category_slug):
    context = dict()
    context['category'] = get_object_or_404(Category, slug=category_slug)
    #Nav:
    # context['categories'] = Category.objects.filter(
    #     status=STATUS,
    # )
    context["items"] = Product.objects.filter(
        category=context['category'],
        status=STATUS,
        stock__gte=1,
    )
    return render(request, "product/category_show.html", context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/detail.html'


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            current_order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object':current_order
            }
            return render(self.request, 'product/summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, 'Yeni bir siparişiniz yok.')
            return redirect('/')
        
        return render(self.request, 'product/summary.html', context)  


@login_required(login_url='..accounts/login/')
def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered = False,
    )

    order_q = Order.objects.filter(user=request.user, ordered=False)
    if order_q.exists():
        order = order_q[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Ürün sepete eklendi")
            return redirect("product:summary")
        else:
            messages.info(request, "Ürün sepete eklendi")
            order.items.add(order_item)
            return redirect("product:summary")
    else:
        ordered_date = timezone.now() 
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "sepete eklendi")
        order.items.add(order_item)
        return redirect("product:summary")
        
      

@login_required(login_url='..accounts/login/')
def remove_single_item(request, slug):
    item = get_object_or_404(Product, slug=slug)

    order_q = Order.objects.filter(user=request.user, ordered=False)
    if order_q.exists():
        order = order_q[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            if (order_item.quantity > 1):
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)

            messages.info(request, "Sepet güncellendi")
            return redirect("product:summary")
        else:
            messages.info(request, "Ürün sepetinizde yok")
            return redirect("product:detail")
    else:
        messages.info(request, "aktif bir sipariniz yok")
        return redirect("product:detail", slug=slug)
      

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            order.items.remove(order_item)
            messages.info(request, "Sepetten ürün silindi")
            return redirect("product:summary")
        else:
            # you can add a message saying the order does not contain the item
            messages.info(request, "Bu ürün sepetinizde yok")
            return redirect("product:sumary")

    else:
        # add a message, no order
        messages.info(request, "Etkin bir siparişiniz yok")
        return redirect("product:sumary")
    

product/templates/product/category_product.html
<div class="card mb-3">
    {% if item.cover_image %}
    <img src="{{ item.cover_image }}" alt="Card image" class="w-100">
    {% endif%}
    <div class="card-body">
      <p class="card-text">
        {{ item.title }}
      </p>
    </div>
    
    <div class="card-body">
      <a href="#" class="card-link">{{ item.price }} TL</a>
      <a href="#" class="card-link">{{ item.stock }} ADET</a>
    </div>
    
  </div>

product/templates/product/category_show.html
{% extends 'core/base.html' %}

{% block container-fluid %}
<div class="container mt-5">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ category.title }} </h2>
            <div class="row">
            {% for item in items %}
                {% if item.cover_image %}
                    <div class="col-sm-4">
                        {% include 'product/product.html' %}
                    </div>
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock container-fluid %}

product/templates/product/detail.html
{% extends 'core/base.html' %}

{% block title %} E-Trade | {{ object.title }} {% endblock title %}


{% block container-fluid %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 justify-content-center">
            <div class="col-md-4 mb5">
                <!--Product image-->
                <img 
                    class="card-img-top p-2" 
                    src="{{ object.cover_image.url }}" alt="..."
                    style="max-height: 300px; width: auto;"    
                >
            </div>

            <div class="col-md-8 mb-5">
                <h5 class="fw-bolder">{{ object.title }}</h5>
                {% if object.discount_price %}
                    <p><del class="mt-2 text-danger">{{ object.price }} TL</del></p>
                    <p>{{ object.discount_price }} TL</p>
                    <span class="badge rounded-pill bg-danger">
                        %{{ object.get_discount_percent|floatformat:2 }} indirim.
                    </span>
                {% else %}
                    <p>{{ object.price }} TL</p>
                {% endif %}
                <span class="badge rounded-pill bg-info">{{ object.category.title }}</span>
                <span class="badge rounded-pill bg-info">{{ object.title }}</span>
                
                <p>{{ object.content }}</p> 
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center">
                        <a class="btn btn-outline-dark mt-auto me-4"  
                            href="{% url 'home' %}">Alışverişe Devam 
                            <i class="bi bi-cart-fill"></i>
                        </a>
                        
                        <a class="btn btn-outline-dark mt-auto"  
                            href="{{ object.get_add_to_cart }}">Sepete Ekle<i class="bi-cart-fill me-1"></i></a>
                    </div>
                </div>
            </div>            
        </div>
    </div>
</section>

{% endblock container-fluid %}

product/templates/product/product.html
<div class="card mb-3">
  {% if item.cover_image %}
  <img src="{{ item.cover_image.url }}" alt="Card image" class="w-100">
  {% endif%}
  <div class="card-body">
    <h5 class="fw-bolder">{{ item.title }}</h5>
    <p class="btn btn-success btn-sm">{{ item.category.title }}</p>
    <!-- Product price-->
    {% if item.discount_price %}
    <p><del class="mt-2 text-danger">{{ item.price|floatformat:"2g" }} TL</del></p>
    <p>{{ item.discount_price|floatformat:"2g" }} TL</p>
    <span class="badge rounded-pill bg-danger">
      %{{ item.get_discount_percent|floatformat:"2g" }} indirim.
    </span>
    {% else %}
    <p>{{ item.price|floatformat:"2g" }} TL</p>
    {% endif %}

    <a href="{{ item.get_item_url }}" class="btn mt-auto ">
      Sepete Ekle
    </a>
  </div>
</div>

product/templates/product/summary.html
{% extends 'core/base.html' %}


{% block container-fluid %}
<section class="py-5">
    <div class="container-fluid table-responsive col-sm-8">
        <h3>Sepetinizdeki Ürünler</h3>
        <br>
        <table class="table table-info">
            <thead class="table-dark">
                <tr>
                    <th scope="col"></th>
                    <th scope="col">#</th>
                    <th scope="col">Ürün</th>
                    <th scope="col">Fiyat</th>
                    <th scope="col">Miktar</th>
                    <th scope="col">Toplam Tutar</th>
                </tr>
            </thead>
            <tbody>
                {% for order_item in object.items.all %}

                <tr>
                    <th scope="row">
                        <a href="{% url 'product:remove-from-cart' order_item.item.slug %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-check-square-fill" viewBox="0 0 16 16">
                                <path
                                    d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 1 .011 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.75.75 0 0 1 1.08-.022z" />
                            </svg>
                        </a>
                    </th>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ order_item.item.title }}</td>
                    {% if order_item.item.discount_price %}
                    <td>{{ order_item.item.discount_price|floatformat:"2g" }} TL</td>
                    {% else %}
                    <td>{{ order_item.item.price|floatformat:"2g" }} TL</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'product:remove_single_item' order_item.item.slug %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-dash-square mr-3" viewBox="0 0 16 16">
                                <path
                                    d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                                <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z" />
                            </svg>
                        </a>
                        {{ order_item.quantity }}
                        <a href="{% url 'product:add_to_cart' order_item.item.slug %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-plus-square ml-3" viewBox="0 0 16 16">
                                <path
                                    d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                                <path
                                    d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                            </svg>
                        </a>
                    </td>
                    {% if order_item.item.discount_price %}
                    <td>{{ order_item.total_item_discount_price|floatformat:"2g" }} TL
                        <span class="badge rounded-pill bg-info ml-2">
                            Kazanç: {{ order_item.amount_saved|floatformat:"2g" }}
                        </span>
                    </td>
                    {% else %}
                    <td>{{ order_item.total_item_price|floatformat:"2g" }} TL</td>
                    {% endif %}
                </tr>
                {% endfor %}


                {% if object.total_price %}

                <tr class="table-group-divider">
                    <td colspan="5"><b>Sepet Tutarı</b></td>
                    <td><b>{{ object.total_price|floatformat:"2g" }} TL</b></td>
                </tr>

                {% endif %}

                <tr class="table-group-divider">
                    <td colspan="3"></td>
                    <td colspan="3">
                            <a href="/" 
                            class="btn btn-info  float-end">
                            Alışverişe Devam Et
                        </a>
                        <a href="{% url 'cart:address' %}" 
                        class="btn btn-primary btn-lg float-end">
                            Sepeti Onayla
                        </td>
                </tr>
            </tbody>
        </table>
    </div>
</section>

{% endblock %}